### ISSUE TITLE
Plug/unplug AC adapter is not detected

### ISSUE THREAD

**Issue by Anycubic** [terminet85/CoreBook_X_Gen8_JCorB_OC#1]
Hello, I read your note in the old issue thread on reboldini "I patched method _Q0A, in order to get update from plug/unplug AC adapter" for the latest `SSDT-CHUWI-JCorB-BATT.aml` version but unfortunately my Chuwi is not detecting plug/unplug AC cord, i.e. I unplug the AC cord but power status says always "charging". Is this working for you? Thank you

**Comment by terminet85** [comment]
Yes it's working. This fix is involving others component than `SSDT-CHUWI-JCorB-BATT.aml` 
Please wipe and clone with my git your EFI dir and retry.

**Comment by Anycubic** [comment]
Do you mean the ACPI patchs? I'm using them:

![2022-02-03_17-24-34](https://user-images.githubusercontent.com/31375394/152384582-b693da43-ac0a-4283-ac9f-580d5ee88e87.jpg)

Is there anything else I should take care of? I'm using Catalina, I wonder if it is something related to it.

**Comment by terminet85** [comment]
ACPI and Kext, but you must sure you're loading them on config.plist. If you wipe and clone would be easier

**Comment by Anycubic** [comment]
Yes, my mistake! I had a mix & match in the kext folder, now plug/unplug AC is working fine, so I confirm also Catalina is ok
