### ISSUE TITLE
OpenCore 0.7.8 and trackpad not recognized.anymore

### ISSUE THREAD

**Issue by Anycubic** [terminet85/CoreBook_X_Gen8_JCorB_OC#2]
Hello, I tried.to port your repo to OC 0.7.8. Everything works fine and boot seems even faster BUT trackpad is not recognized anymore.
Any hint?

Thanks

**Comment by ivancaas** [comment]
Did you use this EFI without changes? Ive downloaded it yesterday and trackpad works perfectly

**Comment by Anycubic** [comment]
I installed everything from scratch and actually it seems you are right 😉
