### ISSUE TITLE
Automatically wake up

### ISSUE THREAD

**Issue by wchanco** [terminet85/CoreBook_X_Gen8_JCorB_OC#4]
Hi, when I was using the Hackintosh, I noticed that it would wake up in the middle of the night, and if it was closed the next morning I would notice that the keyboard backlight was always on. What does that look like in general?

**Comment by terminet85** [comment]
What are Power Adapter settings under Battery?

**Comment by wchanco** [comment]
<img width="671" alt="image" src="https://user-images.githubusercontent.com/62284440/167344789-831c971b-72c3-4819-b45e-d458317624dd.png">
<img width="671" alt="image" src="https://user-images.githubusercontent.com/62284440/167344802-8c43872a-adfe-445f-937c-dfd5dfbcb573.png">
this is for battery
<img width="590" alt="image" src="https://user-images.githubusercontent.com/62284440/167344862-945b1952-0514-44e7-b130-9d40d4306dba.png">
this is for ac
<img width="590" alt="image" src="https://user-images.githubusercontent.com/62284440/167344951-dc54b526-d2ef-4dea-bf24-bf9781966248.png">

**Comment by wchanco** [comment]
and just now when I wake up my hackintosh,The screen is so dark that I can barely see it.And I used battery.

**Comment by terminet85** [comment]
Please remove:
Wake for network access
Enable Power Nap while plugged into a power adapter

**Comment by terminet85** [comment]
> and just now when I wake up my hackintosh,The screen is so dark that I can barely see it.And I used battery.

Looking for replicate this.

**Comment by wchanco** [comment]
OK，thank you.
