### ISSUE TITLE
Hi, Is there any reference value for this acpi patch?

### ISSUE THREAD

**Issue by pymoni** [terminet85/CoreBook_X_Gen8_JCorB_OC#6]
This is from weachy. Broadcom network card version
Version：CoreBookX_2022_JCorB

<removed>

**Comment by terminet85** [comment]
Sorry I don't understand what this your question.

**Comment by pymoni** [comment]
no question. Just offering a patch from weachy. Would like to ask, which of these patches are useful, such as identifying fan speed.

**Comment by terminet85** [comment]
ah thank you, but is a different hardware version that doesn't work (different ACPI tables)

Reference: https://github.com/weachy/CoreBookX-14-Hackintosh/issues/22

**Comment by pymoni** [comment]
The motherboard model of this version I provide is JCorB. Actually weachy did a patch for this model, just not posted on GitHub, for a fee.

**Comment by terminet85** [comment]
You should do not release a closed-source software...
